//! `EventKind` — wire-format event-type identifier. Sprint 1 M1 subset.
//!
//! The enum deliberately does NOT derive `Serialize`/`Deserialize`. The
//! on-disk and in-memory wire format is the dotted string returned by
//! `as_str()` (e.g. `"schema.initialized"`); deriving `serde` with
//! `rename_all = "snake_case"` would produce a divergent string
//! (`"schema_initialized"`) and silently break the round-trip with the
//! `events.kind` column. Use `EventKind::from_str` / `TryFrom<&str>`
//! to decode; `Event` (in `payload.rs`) is the serde-tagged sum type
//! that uses these strings explicitly per variant.

use voom_core::VoomError;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EventKind {
    SchemaInitialized,
    JobOpened,
    JobSucceeded,
    JobFailed,
    JobCancelled,
    TicketCreated,
    TicketReady,
    TicketLeased,
    TicketSucceeded,
    TicketFailedRetriable,
    TicketFailedTerminal,
    TicketRequeuedAfterLeaseExpiry,
    TicketRequeuedAfterForceRelease,
    LeaseAcquired,
    LeaseReleased,
    LeaseExpired,
    LeaseForceReleased,
    NodeRegistered,
    NodeHeartbeatRecorded,
    NodeMarkedStale,
    NodeRetired,
    WorkerRegistered,
    WorkerLinkedToNode,
    WorkerCapabilityRecorded,
    WorkerGrantRecorded,
    WorkerRetired,
    ArtifactHandleCreated,
    ArtifactLocationRecorded,
    ArtifactLocationRetired,
    ArtifactLineageRecorded,
    // Sprint 11 — staged artifact lifecycle.
    ArtifactStaged,
    ArtifactVerificationStarted,
    ArtifactVerificationSucceeded,
    ArtifactVerificationFailed,
    ArtifactCommitStarted,
    ArtifactCommitCompleted,
    ArtifactCommitFailedPreMutation,
    ArtifactCommitRecoveryRequired,
    ArtifactTranscodeStarted,
    ArtifactTranscodeProgress,
    ArtifactTranscodeSucceeded,
    ArtifactTranscodeFailed,
    ArtifactRemuxStarted,
    ArtifactRemuxProgress,
    ArtifactRemuxSucceeded,
    ArtifactRemuxFailed,
    ArtifactAudioTranscodeStarted,
    ArtifactAudioTranscodeProgress,
    ArtifactAudioTranscodeSucceeded,
    ArtifactAudioTranscodeFailed,
    ArtifactAudioExtractStarted,
    ArtifactAudioExtractProgress,
    ArtifactAudioExtractSucceeded,
    ArtifactAudioExtractFailed,
    IssueOpened,
    IssueUpdated,
    IssueResolved,
    // M2 — identity layer.
    MediaWorkCreated,
    MediaVariantCreated,
    AssetBundleCreated,
    AssetBundleMemberAdded,
    AssetBundleMemberRemoved,
    FileAssetCreated,
    FileVersionCreated,
    FileLocationRecorded,
    FileLocationAliased,
    FileLocationRetiredByMove,
    FileLocationRecordedByMove,
    IdentityEvidenceRecorded,
    IdentityEvidenceAccepted,
    IdentityEvidenceSuperseded,
    MediaSnapshotRecorded,
    // M3 — asset use leases (Phase 1).
    UseLeaseAcquired,
    UseLeaseReleased,
    UseLeaseExpired,
    UseLeaseForceReleased,
    UseLeaseRecoveredStaleIssuer,
    UseLeaseReanchoredByMove,
    // M3 Phase 2 — commit safety gate (Phase A subset).
    CommitIntentRecorded,
    CommitAbortedByUseLease,
    CommitAbortedByStaleEvidence,
    CommitAbortedByClosureIncomplete,
    CommitAbortedByPendingCommit,
    // M3 Phase 2 — commit safety gate (Phase B).
    CommitAuthorized,
    CommitAbortedByClosureGrew,
    // M3 Phase 2 — commit safety gate (Phase C).
    CommitCompleted,
    CommitAbortedPostMutation,
    CommitAbortedPreMutation,
    CommitRecoveryRequired,
    CommitForcedOverride,
    // Sprint 17 T15 — external-system lifecycle.
    ExternalSystemRegistered,
    ExternalSystemHealthChanged,
    ExternalSystemLinked,
    ExternalSystemUnlinked,
    ExternalSystemSynced,
}

impl EventKind {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::SchemaInitialized => "schema.initialized",
            Self::JobOpened => "job.opened",
            Self::JobSucceeded => "job.succeeded",
            Self::JobFailed => "job.failed",
            Self::JobCancelled => "job.cancelled",
            Self::TicketCreated => "ticket.created",
            Self::TicketReady => "ticket.ready",
            Self::TicketLeased => "ticket.leased",
            Self::TicketSucceeded => "ticket.succeeded",
            Self::TicketFailedRetriable => "ticket.failed_retriable",
            Self::TicketFailedTerminal => "ticket.failed_terminal",
            Self::TicketRequeuedAfterLeaseExpiry => "ticket.requeued_after_lease_expiry",
            Self::TicketRequeuedAfterForceRelease => "ticket.requeued_after_force_release",
            Self::LeaseAcquired => "lease.acquired",
            Self::LeaseReleased => "lease.released",
            Self::LeaseExpired => "lease.expired",
            Self::LeaseForceReleased => "lease.force_released",
            Self::NodeRegistered => "node.registered",
            Self::NodeHeartbeatRecorded => "node.heartbeat_recorded",
            Self::NodeMarkedStale => "node.marked_stale",
            Self::NodeRetired => "node.retired",
            Self::WorkerRegistered => "worker.registered",
            Self::WorkerLinkedToNode => "worker.linked_to_node",
            Self::WorkerCapabilityRecorded => "worker.capability_recorded",
            Self::WorkerGrantRecorded => "worker.grant_recorded",
            Self::WorkerRetired => "worker.retired",
            Self::ArtifactHandleCreated => "artifact_handle.created",
            Self::ArtifactLocationRecorded => "artifact_location.recorded",
            Self::ArtifactLocationRetired => "artifact_location.retired",
            Self::ArtifactLineageRecorded => "artifact_lineage.recorded",
            Self::ArtifactStaged => "artifact.staged",
            Self::ArtifactVerificationStarted => "artifact.verification_started",
            Self::ArtifactVerificationSucceeded => "artifact.verification_succeeded",
            Self::ArtifactVerificationFailed => "artifact.verification_failed",
            Self::ArtifactCommitStarted => "artifact.commit_started",
            Self::ArtifactCommitCompleted => "artifact.commit_completed",
            Self::ArtifactCommitFailedPreMutation => "artifact.commit_failed_pre_mutation",
            Self::ArtifactCommitRecoveryRequired => "artifact.commit_recovery_required",
            Self::ArtifactTranscodeStarted => "artifact.transcode_started",
            Self::ArtifactTranscodeProgress => "artifact.transcode_progress",
            Self::ArtifactTranscodeSucceeded => "artifact.transcode_succeeded",
            Self::ArtifactTranscodeFailed => "artifact.transcode_failed",
            Self::ArtifactRemuxStarted => "artifact.remux_started",
            Self::ArtifactRemuxProgress => "artifact.remux_progress",
            Self::ArtifactRemuxSucceeded => "artifact.remux_succeeded",
            Self::ArtifactRemuxFailed => "artifact.remux_failed",
            Self::ArtifactAudioTranscodeStarted => "artifact.audio_transcode_started",
            Self::ArtifactAudioTranscodeProgress => "artifact.audio_transcode_progress",
            Self::ArtifactAudioTranscodeSucceeded => "artifact.audio_transcode_succeeded",
            Self::ArtifactAudioTranscodeFailed => "artifact.audio_transcode_failed",
            Self::ArtifactAudioExtractStarted => "artifact.audio_extract_started",
            Self::ArtifactAudioExtractProgress => "artifact.audio_extract_progress",
            Self::ArtifactAudioExtractSucceeded => "artifact.audio_extract_succeeded",
            Self::ArtifactAudioExtractFailed => "artifact.audio_extract_failed",
            Self::IssueOpened => "issue.opened",
            Self::IssueUpdated => "issue.updated",
            Self::IssueResolved => "issue.resolved",
            Self::MediaWorkCreated => "media_work.created",
            Self::MediaVariantCreated => "media_variant.created",
            Self::AssetBundleCreated => "asset_bundle.created",
            Self::AssetBundleMemberAdded => "asset_bundle.member_added",
            Self::AssetBundleMemberRemoved => "asset_bundle.member_removed",
            Self::FileAssetCreated => "file_asset.created",
            Self::FileVersionCreated => "file_version.created",
            Self::FileLocationRecorded => "file_location.recorded",
            Self::FileLocationAliased => "file_location.aliased",
            Self::FileLocationRetiredByMove => "file_location.retired_by_move",
            Self::FileLocationRecordedByMove => "file_location.recorded_by_move",
            Self::IdentityEvidenceRecorded => "identity_evidence.recorded",
            Self::IdentityEvidenceAccepted => "identity_evidence.accepted",
            Self::IdentityEvidenceSuperseded => "identity_evidence.superseded",
            Self::MediaSnapshotRecorded => "media_snapshot.recorded",
            Self::UseLeaseAcquired => "use_lease.acquired",
            Self::UseLeaseReleased => "use_lease.released",
            Self::UseLeaseExpired => "use_lease.expired",
            Self::UseLeaseForceReleased => "use_lease.force_released",
            Self::UseLeaseRecoveredStaleIssuer => "use_lease.recovered_stale_issuer",
            Self::UseLeaseReanchoredByMove => "use_lease.reanchored_by_move",
            Self::CommitIntentRecorded => "commit.intent_recorded",
            Self::CommitAbortedByUseLease => "commit.aborted_by_use_lease",
            Self::CommitAbortedByStaleEvidence => "commit.aborted_by_stale_evidence",
            Self::CommitAbortedByClosureIncomplete => "commit.aborted_by_closure_incomplete",
            Self::CommitAbortedByPendingCommit => "commit.aborted_by_pending_commit",
            Self::CommitAuthorized => "commit.authorized",
            Self::CommitAbortedByClosureGrew => "commit.aborted_by_closure_grew",
            Self::CommitCompleted => "commit.completed",
            Self::CommitAbortedPostMutation => "commit.aborted_post_mutation",
            Self::CommitAbortedPreMutation => "commit.aborted_pre_mutation",
            Self::CommitRecoveryRequired => "commit.recovery_required",
            Self::CommitForcedOverride => "commit.forced_override",
            Self::ExternalSystemRegistered => "external_system.registered",
            Self::ExternalSystemHealthChanged => "external_system.health_changed",
            Self::ExternalSystemLinked => "external_system.linked",
            Self::ExternalSystemUnlinked => "external_system.unlinked",
            Self::ExternalSystemSynced => "external_system.synced",
        }
    }

    /// Parse the on-disk wire-format string into an `EventKind`. Mirrors
    /// `as_str()` exactly — every variant must round-trip.
    ///
    /// # Errors
    /// Returns `VoomError::Database` if the string is not one of the
    /// known dotted wire-format values.
    #[expect(
        clippy::should_implement_trait,
        reason = "explicit inherent fn keeps the dotted wire format the single source of truth; \
                  std::str::FromStr would mask the dedicated VoomError-bearing API"
    )]
    #[expect(
        clippy::too_many_lines,
        reason = "one flat wire-string arm per EventKind variant; splitting the mirror of \
                  as_str() across helpers would hide the round-trip contract"
    )]
    pub fn from_str(s: &str) -> Result<Self, VoomError> {
        Ok(match s {
            "schema.initialized" => Self::SchemaInitialized,
            "job.opened" => Self::JobOpened,
            "job.succeeded" => Self::JobSucceeded,
            "job.failed" => Self::JobFailed,
            "job.cancelled" => Self::JobCancelled,
            "ticket.created" => Self::TicketCreated,
            "ticket.ready" => Self::TicketReady,
            "ticket.leased" => Self::TicketLeased,
            "ticket.succeeded" => Self::TicketSucceeded,
            "ticket.failed_retriable" => Self::TicketFailedRetriable,
            "ticket.failed_terminal" => Self::TicketFailedTerminal,
            "ticket.requeued_after_lease_expiry" => Self::TicketRequeuedAfterLeaseExpiry,
            "ticket.requeued_after_force_release" => Self::TicketRequeuedAfterForceRelease,
            "lease.acquired" => Self::LeaseAcquired,
            "lease.released" => Self::LeaseReleased,
            "lease.expired" => Self::LeaseExpired,
            "lease.force_released" => Self::LeaseForceReleased,
            "node.registered" => Self::NodeRegistered,
            "node.heartbeat_recorded" => Self::NodeHeartbeatRecorded,
            "node.marked_stale" => Self::NodeMarkedStale,
            "node.retired" => Self::NodeRetired,
            "worker.registered" => Self::WorkerRegistered,
            "worker.linked_to_node" => Self::WorkerLinkedToNode,
            "worker.capability_recorded" => Self::WorkerCapabilityRecorded,
            "worker.grant_recorded" => Self::WorkerGrantRecorded,
            "worker.retired" => Self::WorkerRetired,
            "artifact_handle.created" => Self::ArtifactHandleCreated,
            "artifact_location.recorded" => Self::ArtifactLocationRecorded,
            "artifact_location.retired" => Self::ArtifactLocationRetired,
            "artifact_lineage.recorded" => Self::ArtifactLineageRecorded,
            "artifact.staged" => Self::ArtifactStaged,
            "artifact.verification_started" => Self::ArtifactVerificationStarted,
            "artifact.verification_succeeded" => Self::ArtifactVerificationSucceeded,
            "artifact.verification_failed" => Self::ArtifactVerificationFailed,
            "artifact.commit_started" => Self::ArtifactCommitStarted,
            "artifact.commit_completed" => Self::ArtifactCommitCompleted,
            "artifact.commit_failed_pre_mutation" => Self::ArtifactCommitFailedPreMutation,
            "artifact.commit_recovery_required" => Self::ArtifactCommitRecoveryRequired,
            "artifact.transcode_started" => Self::ArtifactTranscodeStarted,
            "artifact.transcode_progress" => Self::ArtifactTranscodeProgress,
            "artifact.transcode_succeeded" => Self::ArtifactTranscodeSucceeded,
            "artifact.transcode_failed" => Self::ArtifactTranscodeFailed,
            "artifact.remux_started" => Self::ArtifactRemuxStarted,
            "artifact.remux_progress" => Self::ArtifactRemuxProgress,
            "artifact.remux_succeeded" => Self::ArtifactRemuxSucceeded,
            "artifact.remux_failed" => Self::ArtifactRemuxFailed,
            "artifact.audio_transcode_started" => Self::ArtifactAudioTranscodeStarted,
            "artifact.audio_transcode_progress" => Self::ArtifactAudioTranscodeProgress,
            "artifact.audio_transcode_succeeded" => Self::ArtifactAudioTranscodeSucceeded,
            "artifact.audio_transcode_failed" => Self::ArtifactAudioTranscodeFailed,
            "artifact.audio_extract_started" => Self::ArtifactAudioExtractStarted,
            "artifact.audio_extract_progress" => Self::ArtifactAudioExtractProgress,
            "artifact.audio_extract_succeeded" => Self::ArtifactAudioExtractSucceeded,
            "artifact.audio_extract_failed" => Self::ArtifactAudioExtractFailed,
            "issue.opened" => Self::IssueOpened,
            "issue.updated" => Self::IssueUpdated,
            "issue.resolved" => Self::IssueResolved,
            "media_work.created" => Self::MediaWorkCreated,
            "media_variant.created" => Self::MediaVariantCreated,
            "asset_bundle.created" => Self::AssetBundleCreated,
            "asset_bundle.member_added" => Self::AssetBundleMemberAdded,
            "asset_bundle.member_removed" => Self::AssetBundleMemberRemoved,
            "file_asset.created" => Self::FileAssetCreated,
            "file_version.created" => Self::FileVersionCreated,
            "file_location.recorded" => Self::FileLocationRecorded,
            "file_location.aliased" => Self::FileLocationAliased,
            "file_location.retired_by_move" => Self::FileLocationRetiredByMove,
            "file_location.recorded_by_move" => Self::FileLocationRecordedByMove,
            "identity_evidence.recorded" => Self::IdentityEvidenceRecorded,
            "identity_evidence.accepted" => Self::IdentityEvidenceAccepted,
            "identity_evidence.superseded" => Self::IdentityEvidenceSuperseded,
            "media_snapshot.recorded" => Self::MediaSnapshotRecorded,
            "use_lease.acquired" => Self::UseLeaseAcquired,
            "use_lease.released" => Self::UseLeaseReleased,
            "use_lease.expired" => Self::UseLeaseExpired,
            "use_lease.force_released" => Self::UseLeaseForceReleased,
            "use_lease.recovered_stale_issuer" => Self::UseLeaseRecoveredStaleIssuer,
            "use_lease.reanchored_by_move" => Self::UseLeaseReanchoredByMove,
            "commit.intent_recorded" => Self::CommitIntentRecorded,
            "commit.aborted_by_use_lease" => Self::CommitAbortedByUseLease,
            "commit.aborted_by_stale_evidence" => Self::CommitAbortedByStaleEvidence,
            "commit.aborted_by_closure_incomplete" => Self::CommitAbortedByClosureIncomplete,
            "commit.aborted_by_pending_commit" => Self::CommitAbortedByPendingCommit,
            "commit.authorized" => Self::CommitAuthorized,
            "commit.aborted_by_closure_grew" => Self::CommitAbortedByClosureGrew,
            "commit.completed" => Self::CommitCompleted,
            "commit.aborted_post_mutation" => Self::CommitAbortedPostMutation,
            "commit.aborted_pre_mutation" => Self::CommitAbortedPreMutation,
            "commit.recovery_required" => Self::CommitRecoveryRequired,
            "commit.forced_override" => Self::CommitForcedOverride,
            "external_system.registered" => Self::ExternalSystemRegistered,
            "external_system.health_changed" => Self::ExternalSystemHealthChanged,
            "external_system.linked" => Self::ExternalSystemLinked,
            "external_system.unlinked" => Self::ExternalSystemUnlinked,
            "external_system.synced" => Self::ExternalSystemSynced,
            other => {
                return Err(VoomError::database(format!(
                    "events.kind {other:?} not in EventKind vocab"
                )));
            }
        })
    }
}

impl TryFrom<&str> for EventKind {
    type Error = VoomError;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::from_str(s)
    }
}

#[cfg(test)]
#[path = "kind_test.rs"]
mod tests;
